# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Promotional Banner App"
client_id = "57cc9b5b15bad1341a9ce466122c87d9"
application_url = "https://your-app-url.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://your-app-url.vercel.app/auth/callback",
  "https://localhost:3000/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "promotional-banner-test.myshopify.com"
include_config_on_deploy = true
